# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

import os.path
import re
from pathlib import Path
from textwrap import dedent

from gersemi.runner import find_custom_command_definitions_in_file


FILE_LINE_RE: re.Pattern[str] = re.compile(
    r"^(?P<file>.*):(?P<line>\d+):(?P<column>\d+)$"
)
SPDX_RE: re.Pattern[str] = re.compile(
    r"(?:^|\n)(?P<spdx>"
    r"# SPDX-FileCopyrightText: [^\n]*\n"
    r"# SPDX-License-Identifier: [^\n]*"
    r")(?:\n|$)"
)

root_path = Path(__file__).parent / ".."
rapids_cmake_path = root_path / "rapids-cmake"
generated_stubs_path = (
    root_path
    / "python/gersemi-rapids-cmake/gersemi_rapids_cmake_detail/stubs/rapids"
    / "rapids-cmake/generated"
)

exit_code = 0

# Write stub files
for base_dir, _, files in os.walk(rapids_cmake_path):
    for file in files:
        if file.endswith(".cmake"):
            filename = Path(base_dir) / file
            relative_filename = filename.relative_to(rapids_cmake_path)
            with open(filename) as f:
                contents = f.read()

            definitions = find_custom_command_definitions_in_file(filename)

            stubs_filename = generated_stubs_path / (
                str(relative_filename)[: -len(".cmake")] + ".stubs"
            )
            if definitions:
                os.makedirs(
                    generated_stubs_path / relative_filename.parent,
                    exist_ok=True,
                )
                with open(stubs_filename, "a+") as f:
                    f.seek(0)
                    old_contents = f.read()
                    f.seek(0)
                    f.truncate()

                    if spdx_match := SPDX_RE.search(contents):
                        f.write(f"{spdx_match.group('spdx')}\n")
                    f.write(
                        "# Automatically generated by ci/regenerate_stubs.py. "
                        "DO NOT EDIT!\n"
                    )

                    for definition in definitions.values():
                        ((entry, file_line),) = definition
                        name_token, (args, keywords), _ = entry

                        file_line_match = FILE_LINE_RE.search(file_line)
                        assert file_line_match
                        assert (
                            Path(file_line_match.group("file")).relative_to(
                                rapids_cmake_path
                            )
                            == relative_filename
                        )

                        f.write(
                            dedent(f"""
                                # Generated from rapids-cmake/{relative_filename}:{file_line_match.group("line")}:{file_line_match.group("column")}
                                function({name_token.value}{"".join([f" {arg}" for arg in args])})
                                  set(options "{";".join(keywords.options)}")
                                  set(one_value "{";".join(keywords.one_value_keywords)}")
                                  set(multi_value "{";".join(keywords.multi_value_keywords)}")
                                  cmake_parse_arguments(_RAPIDS "${{options}}" "${{one_value}}" "${{multi_value}}" ${{ARGN}})
                                endfunction()
                                """)  # noqa: E501
                        )

                    f.seek(0)
                    if f.read() != old_contents:
                        exit_code = 1

            else:
                try:
                    os.remove(stubs_filename)
                except FileNotFoundError:
                    pass
                else:
                    exit_code = 1

# Clean up stale stub files
for base_dir, _, files in os.walk(generated_stubs_path):
    for file in files:
        if file.endswith(".stubs"):
            filename = Path(base_dir) / file
            relative_filename = filename.relative_to(generated_stubs_path)
            if not os.path.exists(
                rapids_cmake_path
                / (str(relative_filename)[: -len(".stubs")] + ".cmake")
            ):
                os.remove(filename)
                exit_code = 1

exit(exit_code)
